### ISSUE TITLE
Removes non-commented code.

### ISSUE THREAD

**Issue by jub0t** [plibither8/vscode-remove-comments#28]
So I removed all comments from my file and the extension remove everything after the `//` in my string. 

**Before**
```js
app.listen(7000, () => {
  console.log("Server is running at http://127.0.0.1:7000");
});
```

**After**
```js
app.listen(7000, () => {
  console.log("Server is running at http:
});
```

**Comment by cbserra** [comment]
Yes, same here. Executing `Remove All Comments` in a CSS file truncated my `@import` of a Google Font:

```
@import url("https://fonts.googleapis.com/css2?...");
```
=>
```
@import url("https:
```

Also, CSS doesn't support `//` comments, only the multi-line variant (`/* ... */`)

I guess one solution to try, is to not remove content following a comment delimiter inside quotations?

**Comment by rioj7** [comment]
@jareer12 @cbserra 

It looks like this is no longer maintained and it can only handle 1 type of line and block comment.

There is an alternative extensions that removes comments and it should detect literal strings and skip there content: [Remove Comments](https://marketplace.visualstudio.com/items?itemName=rioj7.vscode-remove-comments)
