### ISSUE TITLE
cannot remove comment in js react

### ISSUE THREAD

**Issue by qlife1146** [plibither8/vscode-remove-comments#30]
vscode version: 1.74.2
my comment format is `{/* ...multilines... */}`.
but, cannot remove this comment. how to remove multilines comment in js react?

**Comment by rioj7** [comment]
@qlife1146 

Do you mean your comment separators are `{/*` and `*/}`?

Do you have a link describing this as comment separators.

I found: https://www.wisdomgeek.com/development/web-development/react/how-to-write-comments-in-react-jsx/

What is the languageID of these JSX files? ?? `javascriptreact`

If you create an issue at the other extension I will update that.

----

It looks like this is no longer maintained and it can only handle 1 type of line and block comment.

There is an alternative extensions that removes comments and it is possible to also remove the JDOC comments: [Remove Comments](https://marketplace.visualstudio.com/items?itemName=rioj7.vscode-remove-comments)

**Comment by rioj7** [comment]
@qlife1146 [Remove Comments](https://marketplace.visualstudio.com/items?itemName=rioj7.vscode-remove-comments) v1.5.2 supports this comment style for JavaScript React

**Comment by qlife1146** [comment]
oh, thank you so much
