### ISSUE TITLE
Cannot remove JSON comments

### ISSUE THREAD

**Issue by jwjames** [plibither8/vscode-remove-comments#6]
When I try to run this on a JSON file, I get:
`Cannot remove comments: unknown language (json)`

**Comment by plibither8** [comment]
Hi Jeff, 

Currently, the extension supports the removal of comments on "JSON with comments" files, ie, `.jsonc` files. Read more about them [here](https://komkom.github.io).

`.json` files, as is, do not support comments of any type in their syntax, so I guess it's redundant to add a feature for something which the language itself disallows. Please tell me what you feel.

Thanks :+1:

**Comment by jwjames** [comment]
That makes sense! Thank you.
